### ISSUE TITLE
Dropdown widget does not work?

### ISSUE THREAD

**Issue by andyneer** [flexxui/flexx#419]
I've trying to run this example:

from flexx import app, event, ui

```
class Example(ui.Widget):

    CSS = '''
        .flx-DropdownContainer > .flx-TreeWidget {
            min-height: 150px;
        }
    '''

    def init(self):

        # A nice and cosy tree view
        with ui.DropdownContainer(text='Scene graph'):
            with ui.TreeWidget(max_selected=1):
                for i in range(20):
                    ui.TreeItem(text='foo %i' % i, checked=False)

        # A combobox
        self.combo = ui.ComboBox(editable=True,
                                 options=('foo', 'bar', 'spaaaaaaaaam', 'eggs'))
        self.label = ui.Label()

    class JS:

        @event.connect('combo.text')
        def on_combobox_text(self, *events):
            self.label.text = 'Combobox text: ' + self.combo.text
            if self.combo.selected_index is not None:
                self.label.text += ' (index %i)' % self.combo.selected_index
```

but it did not work in Python 2.7 and 3.3. It returns _AttributeError: 'module' object has no attribute 'DropdownContainer'_

This is a very interesting widget in Flexx. How could I make it work?
Thanks.

**Comment by almarklein** [comment]
have you tried with the latest version from Github? The last release has been a while.

(Also, just in case, a heads-up that we're refactoring Flexx; things will improve on many fronts, but the way to write apps will change in a  few ways.)

**Comment by almarklein** [comment]
It works in the latest master.
